"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock, Trophy, Users, BarChart3, Star } from "lucide-react";
import Background from "@/components/layout/Background";
import Sidebar from "@/components/layout/Sidebar";
import Topbar from "@/components/layout/Topbar";
import { useServices } from "@/context/ServiceContext";
import { useDemoMode } from "@/context/DemoModeContext";

export default function LeaderStatisticsPage() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const { services } = useServices();
  const { enabled: demoMode } = useDemoMode();
  const totalServices = services.length;
  const completedServices = useMemo(() => services.filter((s) => s.status === "completed"), [services]);
  const scheduledServices = useMemo(() => services.filter((s) => s.status === "scheduled"), [services]);
  const exchangeServices = useMemo(() => services.filter((s) => s.status === "exchange_requested"), [services]);
  const excusedServices = useMemo(() => services.filter((s) => s.status === "excused"), [services]);
  const totalPoints = useMemo(() => completedServices.reduce((total, s) => total + s.points, 0), [completedServices]);
  const averagePoints = completedServices.length ? Math.round(totalPoints / completedServices.length) : 0;
  const completionRate = totalServices ? Math.round((completedServices.length / totalServices) * 100) : 0;

  return <main className="relative min-h-screen overflow-hidden"><Background /><div className="pointer-events-none fixed inset-x-0 top-0 z-30 h-32 bg-gradient-to-b from-[#050505] via-[#050505]/92 to-transparent" /><Sidebar open={sidebarOpen} onClose={() => setSidebarOpen(false)} /><Topbar sidebarOpen={sidebarOpen} onMenuClick={() => setSidebarOpen(true)} />
    <section className="relative z-10 mx-auto max-w-6xl px-4 pb-12 pt-28 sm:px-6 sm:pt-36">
      <Link href="/leader" className="mb-8 inline-flex items-center gap-2 text-white/55 transition hover:text-white"><ArrowLeft size={18} />Zurück zur Leitung</Link>
      <div className="mb-10"><p className="text-sm uppercase tracking-[0.22em] text-amber-300/80">Leitung</p><h1 className="mt-2 text-3xl font-black tracking-tight text-white sm:text-5xl">Statistiken</h1><p className="mt-3 max-w-2xl text-lg leading-8 text-white/60">Auswertung des aktuell geladenen Supabase-Datenbestands.</p></div>
      {demoMode && <div className="mb-6 rounded-2xl border border-amber-400/20 bg-amber-400/[0.06] p-4 text-sm text-amber-200">Demo-Modus aktiv · Diese Statistik basiert ausschließlich auf den Demo-Diensten.</div>}
      <div className="rounded-[32px] border border-amber-400/20 bg-amber-400/[0.08] p-7 backdrop-blur-2xl"><div className="flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-amber-400/20 bg-amber-400/10 text-amber-300"><BarChart3 size={23} /></div><div><p className="text-sm uppercase tracking-[0.18em] text-amber-300/70">Gesamtübersicht</p><p className="text-sm text-white/40">Aktueller Datenstand</p></div></div><p className="mt-6 text-6xl font-black tracking-tight text-white">{totalServices}</p><p className="mt-1 text-white/45">Dienste insgesamt</p></div><div className="grid gap-3 sm:grid-cols-3"><StatisticBox icon={<CheckCircle2 size={18} />} value={completedServices.length} label="Abgeschlossen" /><StatisticBox icon={<Trophy size={18} />} value={totalPoints} label="Punkte vergeben" /><StatisticBox icon={<Star size={18} />} value={`${completionRate}%`} label="Abschlussrate" /></div></div></div>
      {!totalServices ? <EmptyStatistics /> : <><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatisticCard icon={<CalendarDays size={21} />} value={scheduledServices.length} label="Eingeplant" description="Aktiv geplante Dienste" /><StatisticCard icon={<CheckCircle2 size={21} />} value={completedServices.length} label="Abgeschlossen" description="Bereits erledigte Dienste" /><StatisticCard icon={<Users size={21} />} value={exchangeServices.length} label="Vertretung gesucht" description="Aktuell in der Tauschbörse" /><StatisticCard icon={<Clock size={21} />} value={excusedServices.length} label="Abgemeldet" description="Entschuldigte Dienste" /></div><div className="mt-10 grid gap-4 lg:grid-cols-2"><div className="rounded-[30px] border border-white/10 bg-white/[0.045] p-7 backdrop-blur-2xl"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-amber-400/15 bg-amber-400/10 text-amber-300"><Trophy size={20} /></div><div><p className="text-sm uppercase tracking-[0.18em] text-white/40">Punktesystem</p><h2 className="mt-1 text-xl font-bold text-white">Punkteübersicht</h2></div></div><div className="mt-8 grid grid-cols-2 gap-4"><div><p className="text-sm text-white/40">Vergebene Punkte</p><p className="mt-2 text-3xl font-black text-white">{totalPoints}</p></div><div><p className="text-sm text-white/40">Ø pro Dienst</p><p className="mt-2 text-3xl font-black text-amber-300">{averagePoints}</p></div></div></div><div className="rounded-[30px] border border-white/10 bg-white/[0.045] p-7 backdrop-blur-2xl"><p className="text-sm uppercase tracking-[0.18em] text-white/40">Dienststatus</p><h2 className="mt-2 text-xl font-bold text-white">Aktuelle Verteilung</h2><div className="mt-6 space-y-4"><StatusRow label="Eingeplant" value={scheduledServices.length} /><StatusRow label="Abgeschlossen" value={completedServices.length} /><StatusRow label="Vertretung gesucht" value={exchangeServices.length} /><StatusRow label="Abgemeldet" value={excusedServices.length} /></div></div></div></>}
    </section></main>;
}
function EmptyStatistics() { return <div className="mt-10 rounded-[30px] border border-white/10 bg-white/[0.045] p-10 text-center"><BarChart3 size={34} className="mx-auto text-white/20" /><h2 className="mt-4 text-xl font-bold text-white">Noch keine Statistikdaten</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/40">Sobald echte Dienste in Supabase vorhanden sind, werden hier die Auswertungen angezeigt.</p></div>; }
function StatisticBox({ icon, value, label }: { icon: React.ReactNode; value: string | number; label: string }) { return <div className="min-w-[140px] rounded-2xl border border-white/10 bg-white/[0.04] p-5"><div className="flex items-center gap-2 text-white/40">{icon}<span className="text-xs">{label}</span></div><p className="mt-3 text-2xl font-bold text-white">{value}</p></div>; }
function StatisticCard({ icon, value, label, description }: { icon: React.ReactNode; value: number; label: string; description: string }) { return <div className="rounded-[26px] border border-white/10 bg-white/[0.045] p-5 backdrop-blur-2xl"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-amber-400/15 bg-amber-400/10 text-amber-300">{icon}</div><p className="mt-5 text-3xl font-black text-white">{value}</p><p className="mt-1 font-semibold text-white">{label}</p><p className="mt-2 text-sm leading-6 text-white/40">{description}</p></div>; }
function StatusRow({ label, value }: { label: string; value: number }) { return <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3"><span className="text-sm text-white/55">{label}</span><span className="font-bold text-white">{value}</span></div>; }
